<?php

namespace App\Http\Controllers;

use App\Models\ipfs;
use App\Http\Requests\StoreipfsRequest;
use App\Http\Requests\UpdateipfsRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class IpfsController extends Controller
{
    public function ipfs_create(Request $request)
    {

        $random = Str::random(40);
        $encodedData = explode(',', $request->the_image);
        $encodedData = $encodedData[1];
        $decodedData = base64_decode($encodedData);
        $safeNamePic = $random . '.' . 'png';
        $safeNamejson = $random . '.' . 'json';
        $path =  public_path() . '/storage/account_nft/img/' . $safeNamePic;
        $path_url =  url('') . '/storage/account_nft/img/' . $safeNamePic;
        $path_url_json =  url('') . '/storage/account_nft/json/' . $safeNamejson;
        file_put_contents($path, $decodedData);

        $ipfs = ipfs::create([
            "user_id" => auth()->user()->id,
            "image" => $path_url,
            "json" => $path_url_json,
            "token" => $request->token,
            "wallet" => $request->wallet,
            "firstname" => $request->firstname,
            "lastname" => $request->lastname,
            "email" => $request->email,
            "gendar" => $request->gendar,
            "birthday" => $request->birthday,
            "profession" => $request->profession,
            "education" => $request->education,
            "university" => $request->university,
            "country" => $request->country,
            "city" => $request->city,
            "postalcode" => $request->postalcode,
            "address" => $request->address,
            "phone" => $request->phone,
            "language_first" => $request->language_first,
            "language_second" => $request->language_second,
            "instagram" => $request->instagram,
            "facebook" => $request->facebook,
            "twitter" => $request->twitter,
            "linkedin" => $request->linkedin,
            "whatsapp" => $request->whatsapp,
            "telegram" => $request->telegram,
        ]);
        //bayad ipfso bargardooni
        // return $path_url;
        $json_ipfs =  ([
            "name" => $ipfs->firstname . ' ' . $ipfs->lastname,
            "description" => "Generated by DaoRegister.io Code : $ipfs->token",
            "image" => $path_url,
            "attributes" => [

                [
                    "trait_type" => "wallet",
                    "value" => $ipfs->wallet
                ],
                [
                    "trait_type" => "firstname",
                    "value" => $ipfs->firstname
                ],
                [
                    "trait_type" => "lastname",
                    "value" => $ipfs->lastname
                ],
                [
                    "trait_type" => "email",
                    "value" => $ipfs->email
                ],
                [
                    "trait_type" => "gendar",
                    "value" => $ipfs->gendar
                ],
                [
                    "trait_type" => "birthday",
                    "value" => $ipfs->birthday
                ],
                [
                    "trait_type" => "profession",
                    "value" => $ipfs->profession
                ],
                [
                    "trait_type" => "education",
                    "value" => $ipfs->education
                ],
                [
                    "trait_type" => "university",
                    "value" => $ipfs->university
                ],
                [
                    "trait_type" => "country",
                    "value" => $ipfs->country
                ],
                [
                    "trait_type" => "city",
                    "value" => $ipfs->city
                ],
                [
                    "trait_type" => "postalcode",
                    "value" => $ipfs->postalcode
                ],
                [
                    "trait_type" => "address",
                    "value" => $ipfs->address
                ],
                [
                    "trait_type" => "phone",
                    "value" => $ipfs->phone
                ],
                [
                    "trait_type" => "language_first",
                    "value" => $ipfs->language_first
                ],
                [
                    "trait_type" => "language_second",
                    "value" => $ipfs->language_second
                ],
                [
                    "trait_type" => "instagram",
                    "value" => $ipfs->instagram
                ],
                [
                    "trait_type" => "facebook",
                    "value" => $ipfs->facebook
                ],
                [
                    "trait_type" => "twitter",
                    "value" => $ipfs->twitter
                ],
                [
                    "trait_type" => "linkedin",
                    "value" => $ipfs->linkedin
                ],
                [
                    "trait_type" => "whatsapp",
                    "value" => $ipfs->whatsapp
                ],
                [
                    "trait_type" => "telegram",
                    "value" => $ipfs->telegram
                ],

            ]
        ]);




        Storage::disk('public_uploads')->put("/account_nft/json/" . $safeNamejson, json_encode($json_ipfs));

        return "x";
    }
}
